version: '3.1'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
