version: '3.1'
services:

  asc:
    build: .
    image: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./data/ASC/odoo-web-data:/var/lib/odoo
      - ./data/ASC/config:/etc/odoo
      - ./data/ASC/addons:/mnt/extra-addons

    environment:
      - HOST=db
      - USER=asc
      - PASSWORD=asc

  fte:
    image: odoo
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - ./data/fte/odoo-web-data:/var/lib/odoo
      - ./data/fte/config:/etc/odoo
      - ./data/fte/addons:/mnt/extra-addons

    environment:
      - HOST=db
      - USER=fte
      - PASSWORD=fte

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin12
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
       - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: o.arnold@projektbox.de
      PGADMIN_DEFAULT_PASSWORD: 123
